Throwing a fair dice
#1 the probability space has three components, namely the          sample space, the event space and the probability function
   the sample space is in this case (1,2,3,4,5,6)
#2 the event space here would be throwing (1-1, 1-2, 1-3,1-4,1-    5,1-6,2-1,2-2,2-3,2-4,2-5,2-6,3-1,3-2,3-3,3-4,3-5,3-6,4-1,4-2,4-3,4-4,4-5,4-6,5-1,5-2,5-3,5-4,5-5,5-6,6-1,6-2,6-3,6-4,6-5,6-6.)
#3 the probability of throwing 6 twice is 1/6 * 1/6 = 1/36
#4 we can get 9 by throwing 4 first and then 5, by throwing 5      first and then 4, by throwing 6 first and then 3 and            throwing 3 first and then 6. So the total probability is        1/6*1/6 + 1/6*1/6 + 1/6*1/6 + 1/6*1/6= 1/9

Venn Diagram
#1 
space 1= $U - A - B + (A \cap B)$
space 2 = $A$
space 3 = $A \cap B$
space 4 = $B$
#2 Given: $P(A)= 0,5 P(B)= 0,7 P(A \cup B)= 0,8$
$P(U - A - B + (A \cup B)) = 0$
$P(A) = 0,5$
$P(A \cup B) = P(A) + P(B) - P(A \cap B) = 0,5 + 0,7 - 0,8 = 0,4$
$P(B) = 0,7$

Axioms and Theorems of Probability

#1 As we can see when we draw the venn diagrams we have an area where A and B intersect. If we take the probability of A, we take the probability of the full circle of A, thus including the intersection area. If we then take the probability of B, we take the probability of the full circle of B, again including the intersection area. You can see that we count the intersection area twice. Therefore we have to subtract the probability of the intersection area one time. Therefore $$P(A \cup B) = P(A) + P(B) - P(A \cap B).$$
We could also prove this by assuming that $$P(A \cup B)$$ is not $$P(A) + P(B) - P(A \cap B)$$ and then summing up all the probabilities of the different areas and then we would see that $P(U)$ is not 1, thus violating the second axiom

#2 graphical proof: if we draw the Venn diagrams of A and B where they intersect in the middle, we call the part of circle A which is not intersecting B $(A \cap \lnot B)$ and the part which is intersecting (A n B). Together these parts make A. Therefore, the probability of (A n notB) plus the probability of $(A \cap B)$ is the probability of A. 
algabraic proof: 

#3 $\sum_{i=0}^\infty P(A \cap Bi)$ is equal to $\sum_{i=0}^\infty P(A) + P(B) - P(A u Bi)$. As Bi with i= 1,...n is a partition of U, the summation of Bi therefore is equal to U and thus the probability of Bi is 1 and the probability of $(A \cup B)$ is 1 as well. So we get $\sum_{i=0}^\infty P(A n Bi)$ = $\sum_{i=0}^\infty P(A) + 1 - 1$. As P(A) does not contain an i, $\sum_{i=0}^\infty P(A)$ is just P(A). Thus we indeed get $\sum_{i=0}^\infty P(A n Bi)$ = P(A)

Conditional Probability and Bayes Rule

#1 $P(A|B) + P(\lnot A|B)$ = 1 as well. We make our universe smaller to just the area of B. Then it is the same as $P(A) + P(\lnot A)$, only just in a smaller universe, so the probability is 1.
#2 We can not be sure about this, as we are talking about two different universes. Namely the "B universe" and the "C universe"
#3 $(B \cap \lnot B)$ is the entire universe. So if we are adding the probability of $A$ in $B$ and the probability of $A$ in $ \lnot B$, we get the probability of A in the entire universe, so just $P(A)$. 
#4 conditional probability is defined as: $P(A|B)= P(A n B)/P(B)$. so bayes rule is: $P(A \cap B)/P(B) = (P(A)/P(B)) * (P(A \cap B)/P(A)$. this is equal to $(P(A \cap B)P(B))/P(B) = (P(A \cap B)P(A))/P(A)$. So we get $P(A \cap B) = P(A \cap B)$. So we proved bayes rule. 

Marbles and Vases 

#1 the probability of P(C = "white") is 1/3*5/6 + 1/3*2/3 + 1/3*1/2 = 2/3
#2 That if two independent events A and B happen, their probability is P(A)*P(B)
#3 the probability that you pick a red marble is $P(3/11)$. the probability that if you have a red marble it belonged to vase 1 is $P(1/6)$. 
$$P(red marble, vase 2) = 3/11 * 1/3 = 09.09 $$
$$P(red marble, vase 3) = 3/11 * 1/2 = 0.136$$
$$P(white marble, vase 1) = 8/11 * 5/6$$
$$P(white marble, vase 2) = 8/11 * 2/3$$
$$P(white marble, vase 3) = 8/11 * 1/2$$

In [1]:
import csv

In [2]:
def read_instance(file): 
    #takes a file and reads it, returns the content of that file
    list1 = []
    with open(file, 'r') as file:
        reader = csv.reader(file)
        for i, instance in enumerate(reader):
            instance = [int(i) for i in instance]
            list1 = list1 + [instance]
        return list1

In [7]:
import pandas as pd

In [12]:
import numpy as np

In [46]:
df= pd.read_csv('biometrie2014.csv')
print(df)

   hallo  hallo.1  hallo.2  hallo.3
0     M        60      183     42.0
1     M       130      185     45.0
2     M        84      180     42.0
3     M        65      195     45.0
4     M        55      170     42.0
5      F       63      173     41.0
6     M        74      185     43.0
7      F       50      170     38.0
8      F       82      180     42.0
9     M        77      190     44.0
10    M        76      179     43.0
11    M        66      178     42.0
12    M        79      186     45.0
13    M        76      189     44.0
14    M        75      175     42.0
15    M        90      190     46.0
16    M        70      180     41.0
17     F       46      164     36.0
18    M        98      189     44.0
19    M        79      180     43.0
20    M        67      189     44.0
21    M        81      190     45.3
22    M        85      190     44.5
23    M        75      188     44.0
24    M        70      178     43.0
25    M        60      180     43.0
26    M        73      192  

In [41]:
col1 = df.iloc[:, 0]

In [42]:
print(col1)

0     M 
1     M 
2     M 
3     M 
4     M 
5      F
6     M 
7      F
8      F
9     M 
10    M 
11    M 
12    M 
13    M 
14    M 
15    M 
16    M 
17     F
18    M 
19    M 
20    M 
21    M 
22    M 
23    M 
24    M 
25    M 
26    M 
27    M 
28    M 
29     F
30     F
31    M 
32    M 
Name: hallo, dtype: object


In [39]:
colGewicht2 = df.iloc[:, 1]
print(colGewicht2)

0      60
1     130
2      84
3      65
4      55
5      63
6      74
7      50
8      82
9      77
10     76
11     66
12     79
13     76
14     75
15     90
16     70
17     46
18     98
19     79
20     67
21     81
22     85
23     75
24     70
25     60
26     73
27     76
28     78
29     75
30     50
31     76
32     73
Name: hallo.1, dtype: int64


In [44]:
np.mean(colGewicht2)

73.75757575757575

In [63]:
data = np.genfromtxt(fname='biometrie2014.csv', skip_header=5, delimiter=",",converters={0: lambda x : float(x[0] == 70)})

In [64]:
print(data)

[[   0.    60.   183.    42. ]
 [   0.   130.   185.    45. ]
 [   0.    84.   180.    42. ]
 [   0.    65.   195.    45. ]
 [   0.    55.   170.    42. ]
 [   1.    63.   173.    41. ]
 [   0.    74.   185.    43. ]
 [   1.    50.   170.    38. ]
 [   1.    82.   180.    42. ]
 [   0.    77.   190.    44. ]
 [   0.    76.   179.    43. ]
 [   0.    66.   178.    42. ]
 [   0.    79.   186.    45. ]
 [   0.    76.   189.    44. ]
 [   0.    75.   175.    42. ]
 [   0.    90.   190.    46. ]
 [   0.    70.   180.    41. ]
 [   1.    46.   164.    36. ]
 [   0.    98.   189.    44. ]
 [   0.    79.   180.    43. ]
 [   0.    67.   189.    44. ]
 [   0.    81.   190.    45.3]
 [   0.    85.   190.    44.5]
 [   0.    75.   188.    44. ]
 [   0.    70.   178.    43. ]
 [   0.    60.   180.    43. ]
 [   0.    73.   192.    44. ]
 [   0.    76.   174.    42. ]
 [   0.    78.   187.    44. ]
 [   1.    75.   162.    38. ]
 [   1.    50.   165.    37. ]
 [   0.    76.   188.    44.5]
 [   0. 

In [72]:
females = data[data[:,0]==1]

In [73]:
print(females)

[[   1.   63.  173.   41.]
 [   1.   50.  170.   38.]
 [   1.   82.  180.   42.]
 [   1.   46.  164.   36.]
 [   1.   75.  162.   38.]
 [   1.   50.  165.   37.]]


In [157]:
meanweightfemales = np.mean(females[:,1])
print(meanweightfemales)

61.0


In [158]:
meanheightfemales = np.mean(females[:,2])
print(meanheightfemales)

169.0


In [159]:
meanshoesizefemales = np.mean(females[:,3])
print(meanshoesizefemales)

38.6666666667


In [160]:
males = data[data[:,0]==0]
print(males)

[[   0.    60.   183.    42. ]
 [   0.   130.   185.    45. ]
 [   0.    84.   180.    42. ]
 [   0.    65.   195.    45. ]
 [   0.    55.   170.    42. ]
 [   0.    74.   185.    43. ]
 [   0.    77.   190.    44. ]
 [   0.    76.   179.    43. ]
 [   0.    66.   178.    42. ]
 [   0.    79.   186.    45. ]
 [   0.    76.   189.    44. ]
 [   0.    75.   175.    42. ]
 [   0.    90.   190.    46. ]
 [   0.    70.   180.    41. ]
 [   0.    98.   189.    44. ]
 [   0.    79.   180.    43. ]
 [   0.    67.   189.    44. ]
 [   0.    81.   190.    45.3]
 [   0.    85.   190.    44.5]
 [   0.    75.   188.    44. ]
 [   0.    70.   178.    43. ]
 [   0.    60.   180.    43. ]
 [   0.    73.   192.    44. ]
 [   0.    76.   174.    42. ]
 [   0.    78.   187.    44. ]
 [   0.    76.   188.    44.5]
 [   0.    73.   180.    43. ]]


In [161]:
meanweightmales = np.mean(males[:,1])
print(meanweightmales)

76.5925925926


In [162]:
meanheightmales = np.mean(males[:,2])
print(meanheightmales)

184.074074074


In [163]:
meanshoesizemales = np.mean(males[:,3])
print(meanshoesizemales)

43.4925925926


In [164]:
stdfemalesshoesize = np.std(females[:,3])

In [165]:
stdmaleshoesize = np.std(males[:,3])

In [166]:
stdfemaleweight = np.std(females[:,1])
print(stdfemaleweight)

13.5892114071


In [167]:
stdfemaleheight = np.std(females[:,2])
print(stdfemaleheight)

6.16441400297


In [168]:
stdmaleweight = np.std(males[:,1])
print(stdmaleweight)

13.7847453509


In [201]:
stdmaleheight = np.std(males[:,2])
print(stdmaleheight)

6.10358683815


In [202]:
import math

In [256]:
from math import e
np.e

2.718281828459045

In [220]:
def normalpdfweight(w, mu, sigma):
    return (1/(sigma*(2*2.14)**0.5))*(e**((w-mu)**2)/(2*(sigma)**2))

In [221]:
def normalpdfheight(h, mu, sigma):
    return (1/(sigma*(2*2.14)**0.5))*(e**((h-mu)**2)/(2*(sigma)**2))

In [222]:
def normalpdfshoesize(s, mu, sigma):
    return (1/(sigma*(2*2.14)**0.5))*(e**((s-mu)**2)/(2*(sigma)**2))

In [223]:
def maleweightnormalpdf(w):
    return (normalpdfweight(w, meanweightmales, stdmaleweight))

In [224]:
def maleheightnormalpdf(h):
    return (normalpdf(h, meanheightmales, stdmaleweight))

In [225]:
def maleshoesizenormalpdf(s):
    return (normalpdf(s, meanshoesizemales, stdmaleshoesize))

In [226]:
maleshoesizenormalpdf(44)

0.16563557886371427

In [227]:
def femaleweightnormalpdf(w):
    return (normalpdf(w, meanweightfemales, stdfemaleweight))

In [228]:
def femaleheightnormalpdf(h):
    return (normalpdf(h, meanheightfemales, stdfemaleheight))

In [234]:
def femaleshoesizenormalpdf(s):
    return (normalpdf(s, meanshoesizefemales, stdfemalesshoesize))

In [241]:
def M(w,h,s):
    return (maleweightnormalpdf(w)*maleheightnormalpdf(h)*maleshoesizenormalpdf(s)*(27/33))

In [242]:
def F(w,h,s):
    return (femaleweightnormalpdf(w)*femaleheightnormalpdf(h)*femaleshoesizenormalpdf(s)*(6/33))

In [248]:
def Classify(w,h,s):
    if F(w,h,s) >= M(w,h,s):
        return("Female")
    else:
        return("Male")
   
    




In [249]:
Classify(60,183,42)

'Male'

In [250]:
Classify(6,173,41)

'Male'

In [251]:
Classify(40,150,35)

/Users/charlotteout/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: overflow encountered in double_scalars
  from ipykernel import kernelapp as app


'Female'

In [255]:
for d in data:
    print(d[0], Classify(*d[1:]))

0.0 Male
0.0 Female
0.0 Female
0.0 Female
0.0 Male
1.0 Male
0.0 Female
1.0 Male
1.0 Female
0.0 Female
0.0 Female
0.0 Male
0.0 Female
0.0 Female
0.0 Female
0.0 Female
0.0 Female
1.0 Male
0.0 Female
0.0 Female
0.0 Female
0.0 Female
0.0 Female
0.0 Female
0.0 Female
0.0 Male
0.0 Female
0.0 Female
0.0 Female
1.0 Male
1.0 Male
0.0 Female
0.0 Female


/Users/charlotteout/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: overflow encountered in double_scalars
  from ipykernel import kernelapp as app
